name: Deploy domofon62.ru

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Connect to server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.DOMOFON_HOST }}
          username: ${{ secrets.DOMOFON_USERNAME }}
          key: ${{ secrets.DOMOFON_KEY }}
          script: |
            # cd /var/www/u1079678/data/www/oknamobifon.ru/wp-content/themes/oknamobifon/promo
            # git clone https://github.com/site100ru/oknamobifon-promo.git .
            
            #cd /var/www/u1079678/data/www/oknamobifon.ru/wp-content/themes/oknamobifon/promo
            #git pull
